packages:
  - 'packages/*'

catalogs:
  shared:
    react: '^18.2.0'
    react-dom: '^18.2.0'
    typescript: '^5.3.3'
    zod: '^3.22.4'
    mongodb: '^6.3.0'
    mongoose: '^8.0.0'

  backend:
    '@nestjs/common': '^11.1.8'
    '@nestjs/core': '^11.1.8'
    '@nestjs/typeorm': '^9.0.1'
    typeorm: '^0.3.17'
    socket.io: '^4.7.2'

  frontend:
    vite: '^5.0.7'
    '@vitejs/plugin-react': '^4.2.1'
    shadcn-ui: 'latest'
    tailwindcss: '^3.3.6'
    '@tanstack/react-query': '^5.25.0'
